#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	echo "Okay"
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1 '.'
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo
}

SECONDS=0


do_one z_Inlists/inlist_1_Omega=5d-5 z_Mods/mod_1_Omega=5d-5.mod z_Logs/LOGS_1_Omega=5d-5
do_one z_Inlists/inlist_2_Omega=1d-4 z_Mods/mod_2_Omega=1d-4.mod z_Logs/LOGS_2_Omega=1d-4
do_one z_Inlists/inlist_3_Omega=2d-4 z_Mods/mod_3_Omega=2d-4.mod z_Logs/LOGS_3_Omega=2d-4
do_one z_Inlists/inlist_4_Omega=5d-4 z_Mods/mod_4_Omega=5d-4.mod z_Logs/LOGS_4_Omega=5d-4
do_one z_Inlists/inlist_5_Omega=1d-3 z_Mods/mod_5_Omega=1d-3.mod z_Logs/LOGS_5_Omega=1d-3
do_one z_Inlists/inlist_6_Omega=2d-3 z_Mods/mod_6_Omega=2d-3.mod z_Logs/LOGS_6_Omega=2d-3
do_one z_Inlists/inlist_7_Omega=5d-3 z_Mods/mod_7_Omega=5d-3.mod z_Logs/LOGS_7_Omega=5d-3


echo "Elapsed: $(($SECONDS / 3600)) hrs $((($SECONDS / 60) % 60)) min $(($SECONDS % 60)) sec."
echo 'Finished all inlists.'