#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	echo "Okay"
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1 '.'
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo
}

SECONDS=0


#do_one z_Inlists/inlist_D20 z_Mods/mod_D.mod z_Logs/LOGS_D20
do_one z_Inlists/inlist_D21_noHdiffusion z_Mods/mod_D.mod z_Logs/LOGS_D21_noHdiffusion


echo "Elapsed: $(($SECONDS / 3600)) hrs $((($SECONDS / 60) % 60)) min $(($SECONDS % 60)) sec."
echo 'Finished all inlists.'
