#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	echo "Okay"
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1 '.'
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo
}

SECONDS=0


do_one z_Inlists/inlist_Z=1d-4_M=0p60 z_Mods/mod_Z=1d-4_M=0p60.mod z_Logs/LOGS_Z=1d-4_M=0p60
do_one z_Inlists/inlist_Z=1d-4_M=0p61 z_Mods/mod_Z=1d-4_M=0p61.mod z_Logs/LOGS_Z=1d-4_M=0p61
do_one z_Inlists/inlist_Z=1d-4_M=0p62 z_Mods/mod_Z=1d-4_M=0p62.mod z_Logs/LOGS_Z=1d-4_M=0p62
do_one z_Inlists/inlist_Z=1d-4_M=0p63 z_Mods/mod_Z=1d-4_M=0p63.mod z_Logs/LOGS_Z=1d-4_M=0p63
do_one z_Inlists/inlist_Z=1d-4_M=0p64 z_Mods/mod_Z=1d-4_M=0p64.mod z_Logs/LOGS_Z=1d-4_M=0p64
do_one z_Inlists/inlist_Z=1d-4_M=0p65 z_Mods/mod_Z=1d-4_M=0p65.mod z_Logs/LOGS_Z=1d-4_M=0p65
do_one z_Inlists/inlist_Z=1d-4_M=0p66 z_Mods/mod_Z=1d-4_M=0p66.mod z_Logs/LOGS_Z=1d-4_M=0p66
do_one z_Inlists/inlist_Z=1d-4_M=0p67 z_Mods/mod_Z=1d-4_M=0p67.mod z_Logs/LOGS_Z=1d-4_M=0p67
do_one z_Inlists/inlist_Z=1d-4_M=0p68 z_Mods/mod_Z=1d-4_M=0p68.mod z_Logs/LOGS_Z=1d-4_M=0p68
do_one z_Inlists/inlist_Z=1d-4_M=0p69 z_Mods/mod_Z=1d-4_M=0p69.mod z_Logs/LOGS_Z=1d-4_M=0p69
do_one z_Inlists/inlist_Z=1d-4_M=0p70 z_Mods/mod_Z=1d-4_M=0p70.mod z_Logs/LOGS_Z=1d-4_M=0p70
do_one z_Inlists/inlist_Z=1d-4_M=0p71 z_Mods/mod_Z=1d-4_M=0p71.mod z_Logs/LOGS_Z=1d-4_M=0p71
do_one z_Inlists/inlist_Z=1d-4_M=0p72 z_Mods/mod_Z=1d-4_M=0p72.mod z_Logs/LOGS_Z=1d-4_M=0p72
do_one z_Inlists/inlist_Z=1d-4_M=0p73 z_Mods/mod_Z=1d-4_M=0p73.mod z_Logs/LOGS_Z=1d-4_M=0p73
do_one z_Inlists/inlist_Z=1d-4_M=0p74 z_Mods/mod_Z=1d-4_M=0p74.mod z_Logs/LOGS_Z=1d-4_M=0p74
do_one z_Inlists/inlist_Z=1d-4_M=0p75 z_Mods/mod_Z=1d-4_M=0p75.mod z_Logs/LOGS_Z=1d-4_M=0p75
do_one z_Inlists/inlist_Z=1d-4_M=0p76 z_Mods/mod_Z=1d-4_M=0p76.mod z_Logs/LOGS_Z=1d-4_M=0p76
do_one z_Inlists/inlist_Z=1d-4_M=0p77 z_Mods/mod_Z=1d-4_M=0p77.mod z_Logs/LOGS_Z=1d-4_M=0p77
do_one z_Inlists/inlist_Z=1d-4_M=0p78 z_Mods/mod_Z=1d-4_M=0p78.mod z_Logs/LOGS_Z=1d-4_M=0p78
do_one z_Inlists/inlist_Z=1d-4_M=0p79 z_Mods/mod_Z=1d-4_M=0p79.mod z_Logs/LOGS_Z=1d-4_M=0p79
do_one z_Inlists/inlist_Z=1d-4_M=0p80 z_Mods/mod_Z=1d-4_M=0p80.mod z_Logs/LOGS_Z=1d-4_M=0p80
do_one z_Inlists/inlist_Z=1d-4_M=0p81 z_Mods/mod_Z=1d-4_M=0p81.mod z_Logs/LOGS_Z=1d-4_M=0p81
do_one z_Inlists/inlist_Z=1d-4_M=0p82 z_Mods/mod_Z=1d-4_M=0p82.mod z_Logs/LOGS_Z=1d-4_M=0p82
do_one z_Inlists/inlist_Z=1d-4_M=0p83 z_Mods/mod_Z=1d-4_M=0p83.mod z_Logs/LOGS_Z=1d-4_M=0p83


echo "Elapsed: $(($SECONDS / 3600)) hrs $((($SECONDS / 60) % 60)) min $(($SECONDS % 60)) sec."
echo 'Finished all inlists.'