#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	echo "Okay"
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1 '.'
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo
}

SECONDS=0


#do_one z_Inlists/inlist_0p67B z_Mods/mod_0p67B.mod z_Logs/LOGS_0p67B
#do_one z_Inlists/inlist_0p67D z_Mods/mod_0p67D.mod z_Logs/LOGS_0p67D
#do_one z_Inlists/inlist_0p69B z_Mods/mod_0p69B.mod z_Logs/LOGS_0p69B
do_one z_Inlists/inlist_0p69D z_Mods/mod_0p69D.mod z_Logs/LOGS_0p69D


echo "Elapsed: $(($SECONDS / 3600)) hrs $((($SECONDS / 60) % 60)) min $(($SECONDS % 60)) sec."
echo 'Finished all inlists.'