#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	echo "Okay"
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'Failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'Finished' $1 '.'
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo
}

SECONDS=0


do_one z_Inlists/inlist_01 z_Mods/mod_01.mod z_Logs/LOGS_01
do_one z_Inlists/inlist_02 z_Mods/mod_02.mod z_Logs/LOGS_02
do_one z_Inlists/inlist_03 z_Mods/mod_03.mod z_Logs/LOGS_03
do_one z_Inlists/inlist_04 z_Mods/mod_04.mod z_Logs/LOGS_04
do_one z_Inlists/inlist_05 z_Mods/mod_05.mod z_Logs/LOGS_05
do_one z_Inlists/inlist_06 z_Mods/mod_06.mod z_Logs/LOGS_06
do_one z_Inlists/inlist_07 z_Mods/mod_07.mod z_Logs/LOGS_07
do_one z_Inlists/inlist_08 z_Mods/mod_08.mod z_Logs/LOGS_08
do_one z_Inlists/inlist_09 z_Mods/mod_09.mod z_Logs/LOGS_09
do_one z_Inlists/inlist_10 z_Mods/mod_10.mod z_Logs/LOGS_10
do_one z_Inlists/inlist_11 z_Mods/mod_11.mod z_Logs/LOGS_11
do_one z_Inlists/inlist_12 z_Mods/mod_12.mod z_Logs/LOGS_12
do_one z_Inlists/inlist_13 z_Mods/mod_13.mod z_Logs/LOGS_13
do_one z_Inlists/inlist_14 z_Mods/mod_14.mod z_Logs/LOGS_14
do_one z_Inlists/inlist_15 z_Mods/mod_15.mod z_Logs/LOGS_15
do_one z_Inlists/inlist_16 z_Mods/mod_16.mod z_Logs/LOGS_16
do_one z_Inlists/inlist_17 z_Mods/mod_17.mod z_Logs/LOGS_17
do_one z_Inlists/inlist_18 z_Mods/mod_18.mod z_Logs/LOGS_18
do_one z_Inlists/inlist_19 z_Mods/mod_19.mod z_Logs/LOGS_19
do_one z_Inlists/inlist_20 z_Mods/mod_20.mod z_Logs/LOGS_20


echo "Elapsed: $(($SECONDS / 3600)) hrs $((($SECONDS / 60) % 60)) min $(($SECONDS % 60)) sec."
echo 'Finished all inlists.'